// react/todo-app/src/components/AddTask.jsx
import { useState } from "react";

export default function AddTask({ addTask }) {
  const [taskInput, setTaskInput] = useState("");

  const handleSubmit = () => {
    if (taskInput.trim()) {
      addTask(taskInput);
      setTaskInput("");
    }
  };

  return (
    <div>
      <input value={taskInput} onChange={(e) => setTaskInput(e.target.value)} placeholder="Add a new task..." />
      <button onClick={handleSubmit}>➕ Add</button>
    </div>
  );
}

// vue/todo-app-options-api/src/components/AddTask.vue
<template>
  <div>
    <input v-model="taskInput" placeholder="Add a new task..." />
    <button @click="submitTask">➕ Add</button>
  </div>
</template>

<script>
export default {
  data() {
    return {
      taskInput: ""
    };
  },
  methods: {
    submitTask() {
      if (this.taskInput.trim()) {
        this.$emit("add-task", this.taskInput);
        this.taskInput = "";
      }
    }
  }
};
</script>
