// vue/todo-app-options-api/src/components/TaskFilter.vue
<template>
  <div>
    <label for="filter">Filter:</label>
    <select :value="selectedFilter" @change="$emit('update:selectedFilter', $event.target.value)">
      <option value="All">All</option>
      <option value="Completed">Completed</option>
      <option value="Pending">Pending</option>
    </select>
  </div>
</template>

<script>
export default {
  props: ["selectedFilter"]
};
</script>

// react/todo-app/src/components/TaskFilter.jsx

export default function TaskFilter({ filterOption, setFilterOption }) {
  return (
    <div>
      <label htmlFor="filter">Filter:</label>
      <select value={filterOption} onChange={(e) => setFilterOption(e.target.value)}>
        <option value="All">All</option>
        <option value="Completed">Completed</option>
        <option value="Pending">Pending</option>
      </select>
    </div>
  );
}
