// vue/todo-app/src/components/TodoItem.vue
<script setup>
defineProps(["task"]);
defineEmits(["toggle", "remove"]);
</script>

<template>
  <li>
    <input type="checkbox" :checked="task.done" @change="$emit('toggle')" />
    <span :class="{ done: task.done }">{{ task.text }}</span>
    <button @click="$emit('remove')">❌</button>
  </li>
</template>

<style scoped>
.done { text-decoration: line-through; color: gray; }
</style>

// react/todo-app/src/components/TodoItem.jsx

export default function TodoItem({ task, onToggle, onRemove }) {
  return (
    <li>
      <input type="checkbox" checked={task.done} onChange={() => onToggle(task.id)} />
      <span style={{ textDecoration: task.done ? "line-through" : "none" }}>{task.text}</span>
      <button onClick={() => onRemove(task.id)}>❌</button>
    </li>
  );
}
