// react/todo-app/src/components/AddTask.jsx
import { useState } from "react";

export default function AddTask({ addTask }) {
  const [taskInput, setTaskInput] = useState("");

  const handleSubmit = () => {
    if (taskInput.trim()) {
      addTask(taskInput);
      setTaskInput("");
    }
  };

  return (
    <div>
      <input value={taskInput} onChange={(e) => setTaskInput(e.target.value)} placeholder="Add a new task..." />
      <button onClick={handleSubmit}>➕ Add</button>
    </div>
  );
}

// vue/todo-app/src/components/AddTask.vue
<script setup>
import { ref } from "vue";
import { useTodoStore } from "../store/useTodoStore";

const taskInput = ref("");
const { addTask } = useTodoStore();

const submitTask = () => {
  if (taskInput.value.trim()) {
    addTask(taskInput.value);
    taskInput.value = "";
  }
};
</script>

<template>
  <div>
    <input v-model="taskInput" placeholder="Add a new task..." />
    <button @click="submitTask">➕ Add</button>
  </div>
</template>
