// react/todo-app/src/components/TaskFilter.jsx

export default function TaskFilter({ filterOption, setFilterOption }) {
  return (
    <div>
      <label htmlFor="filter">Filter:</label>
      <select value={filterOption} onChange={(e) => setFilterOption(e.target.value)}>
        <option value="All">All</option>
        <option value="Completed">Completed</option>
        <option value="Pending">Pending</option>
      </select>
    </div>
  );
}

// vue/todo-app/src/components/TaskFilter.vue
<template>
  <div>
    <label for="filter">Filter:</label>
    <select v-model="filterOption">
      <option value="All">All</option>
      <option value="Completed">Completed</option>
      <option value="Pending">Pending</option>
    </select>
  </div>
</template>

<script setup>
import { useTaskFilter } from "../composables/useTaskFilter";

const { filterOption } = useTaskFilter(); // ✅ Reactive filter option
</script>
