// react/todo-app/src/components/TodoList.jsx
import TodoItem from "./TodoItem";
import {useMemo} from "react";
import TaskFilter from "./TaskFilter.jsx";
import {useTaskFilter} from "../hooks/useTaskFilter.js";

export default function TodoList({ tasks, toggleTask, removeTask }) {
  const { filterOption, setFilterOption, filteredTasks } = useTaskFilter(tasks);
  // Compute completed tasks count
  const completedTasks = useMemo(() => tasks.filter(task => task.done), [tasks]);

  // Compute remaining tasks count
  const remainingTasks = tasks.filter(task => !task.done);

  return (
    <>
      <p>✅ Completed: {completedTasks.length}</p>
      <p>📌 Remaining: {remainingTasks.length}</p>

      <TaskFilter filterOption={filterOption} setFilterOption={setFilterOption} />

      <ul>
        {filteredTasks.map(task => (
          <TodoItem key={task.id} task={task} onToggle={toggleTask} onRemove={removeTask} />
        ))}
      </ul>
    </>

  );
}

// vue/todo-app/src/components/TodoList.vue
<script setup>
import TodoItem from "./TodoItem.vue";
import TaskFilter from "./TaskFilter.vue";
import { useTodoStore } from "../store/useTodoStore";
import {computed} from "vue";
import {useTaskFilter} from "../composables/useTaskFilter.js";

const { tasks, toggleTask, removeTask } = useTodoStore();

// Compute the count of completed tasks
const completedTasks = computed(() => tasks.value.filter(task => task.done));

// Compute the count of remaining tasks
const remainingTasks = computed(() => tasks.value.filter(task => !task.done));

const { filteredTasks } = useTaskFilter(tasks); // ✅ Apply filtering logic
</script>

<template>
  <p>✅ Completed: {{ completedTasks.length }}</p>
  <p>📌 Remaining: {{ remainingTasks.length }}</p>

  <TaskFilter />
  <ul>
    <TodoItem
        v-for="task in filteredTasks"
        :key="task.id"
        :task="task"
        @toggle="toggleTask(task.id)"
        @remove="removeTask(task.id)"
    />
  </ul>
</template>
